### ISSUE TITLE
Put first sketch of first draft of manuscript on this repo at the end of week 7

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/meesterproef_joshua#9]
Aim for the minimum complete draft, as if a lazy student with dry humour :+1:

Focus: what are the questions answered by this research?

**Comment by richelbilderbeek** [comment]
J will do in end of week 4

**Comment by DynCoder** [comment]
Je kan vast wel .rtf openen

**Comment by richelbilderbeek** [comment]
Yes I can :+1:

**Comment by richelbilderbeek** [comment]
This is a nice Issue for week 7.

**Comment by richelbilderbeek** [comment]
Obsolete
